# action.yml
name: 'Cloudflare DNSLink via Cloudflare API'
description: 'Update DNS Link with new IPFS Hash via Cloudflare'

inputs:
  cid: # IPFS CID
    description: 'IPFS CID'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
